### ISSUE TITLE
Missing loading screen

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-desktop#25]
Looks like a loading screen [was/is planned](https://github.com/aragon/aragon-desktop/blob/master/src/main.js#L56) but right now it's not there.

Related to (possibly duplicate of) #1

**Comment by luisivan** [comment]
I forgot to commit it, so committed it to this other branch https://github.com/aragon/aragon-desktop/tree/loading-file

**Comment by onbjerg** [comment]
@luisivan I opened a PR with the file from your branch (#31), I hope that's ok 😊

**Comment by onbjerg** [comment]
Fixed in #31
