### ISSUE TITLE
Users cannot access non-aragonid.eth organizations

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-desktop#67]
AFAICT the only organizations that can be accessed in the Aragon Desktop client are organizations that use the `aragonid.eth` domain. This means that users cannot access e.g. `governance.aragonproject.eth` from the desktop client.

**Comment by bpierre** [comment]
It is now possible except for addresses, should we close this issue and track it there? https://github.com/aragon/aragon/issues/1062

**Comment by sohkai** [comment]
@bpierre Let's so do, even though it's been a tad confusing :).
