### ISSUE TITLE
Open organization button not working once we choose the first org

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-desktop#74]
Once we explore an organization is not possible to go back to the Welcome to Aragon page to choose other org or change between Rinkeby and Mainnet.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/9082013/59972902-bf999c80-956d-11e9-9578-ba9b463413ac.png">

**Comment by luisivan** [comment]
Seems like it's broken in the product itself, not with Desktop

**Comment by sohkai** [comment]
This will be fixed in the next release of the client.
