### ISSUE TITLE
Integrated terminal

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-desktop#78]
We can use [`xterm.js`](https://xtermjs.org/) to expose a terminal that has commands like `dao act`, `dao exec`, etc. (the dao cli).

Until the GUI is fully featured people need to use the CLI (which bundles dev commands as well) and which is a hassle to install.

Common use case: changing the quorum of a voting app.

Related: https://github.com/aragon/aragon-cli/issues/583

**Comment by 0x6431346e** [comment]
This could also be the very first *node* app we bring to `aragon-desktop`.

Currently if people want to make Aragon apps that use the Node API, they need to use the `aragon-wrapper` and make it from scratch, which is not very nice. [This should improve for developers](https://forum.aragon.org/t/aragoncli-extensibility/680).

The only problem with this is that users are very exposed as there is no plan for sand-boxing and apps will be using the wrapper, and **file-system** directly, (being able to read keys stored on disk for example).

I suspect this can be achieved using docker though...

**Comment by sohkai** [comment]
> If people want to make Aragon apps that use the Node API

I don't think this will ever be a goal, at least in the current form of the client.

**Comment by 0x6431346e** [comment]
I'm not sure, but I think DappNode apps might be exactly what I have in mind.

E.g.: Installing and running ipfs, checking CPU temperatures, etc.

**Comment by sohkai** [comment]
Closing this, as we are experimenting with an integrated console for organization actions in aragon/aragon.
